---
- name: Install Nginx
  hosts: all
  gather_facts: true
  become: true
  become_user: root
  tasks:
    - include_vars: ./vault.yml
    - name: Install and Configure nginx on the host server
      include_role:
        name: nginx
        tasks_from: main.yml
