---
- name: Server steps run as "oracle"
  hosts: all
  gather_facts: true
  become: true
  become_user: "{{ oracle_user }}"
  tasks:
    - name: Verify that "main_user" extra variable is provided
      fail:
        msg: main_user variable not provided
      when: main_user is undefined

    - name: Site specific Database and APEX configuration roles
      include_role:
        name: "{{ role_list }}"
      loop:
        - "site_database"
        - "site_apex"
      loop_control:
        loop_var: role_list
