SET linesize 180
SET pagesize 32767
SET tab OFF
SET trimspool ON
COL "SERIAL#" FOR 9999999
COL access_method FOR A13
COL account_locked FOR A14
COL acl FOR A48
COL acl_owner FOR A16
COL action_name FOR A26
COL admin_option FOR A12
COL after_row FOR A9
COL algorithm_compatibility FOR A23
COL all_supp FOR A8
COL allocation_type FOR A15
COL allow_app_building_yn FOR A21
COL allow_sql_workshop_yn FOR A21
COL allow_team_development_yn FOR A25
COL anyschema FOR A9
COL application_clone FOR A17
COL application_pdb FOR A15
COL application_root FOR A16
COL application_root_clone FOR A22
COL application_seed FOR A16
COL aq_ha_notifications FOR A19
COL archiver FOR A8
COL assm FOR A4
COL audit_condition FOR A60 WORD_WRAPPED
COL audit_only_toplevel FOR A19
COL audit_option FOR A12
COL audit_type FOR A16
COL authentication FOR A14
COL authentication_method FOR A22
COL authentication_type FOR A19
COL before_row FOR A10
COL bigfile FOR A7
COL binds_captured FOR A14
COL build_mode FOR A10
COL can_purge FOR A9
COL can_undrop FOR A10
COL captured FOR A8
COL cell_flash_cache FOR A16
COL change_password_on_first_use FOR A28
COL char_used FOR A9
COL chunk_tablespace FOR A16
COL clb_goal FOR A8
COL client FOR A20
COL comment_text FOR A40 WORD_WRAPPED
COL common FOR A6
COL composite FOR A9
COL compression FOR A11
COL con_name FOR A20
COL condition_eval_opt FOR A18
COL constraint_type FOR A15
COL current_user FOR A30
COL cycle_flag FOR A10
COL database_name FOR A13
COL dbproxy_username FOR A30
COL dbusername FOR A30
COL def_index_compression FOR A21
COL def_inmemory FOR A12
COL def_inmemory_compression FOR A24
COL def_inmemory_distribute FOR A23
COL def_inmemory_duplicate FOR A22
COL def_inmemory_priority FOR A21
COL def_inmemory_service FOR A20
COL def_inmemory_service_name FOR A25
COL def_tab_compression FOR A19
COL default_password FOR A16
COL default_role FOR A12
COL delegate_option FOR A15
COL dep_wrapped FOR A11
COL description FOR A48 WORD_WRAPPED
COL dictionary_protected FOR A20
COL display_value FOR A32
COL dropped FOR A7
COL droptime_plus_show_recyc FOR A19 HEADING 'DROP TIME'
COL dtp FOR A3
COL dynamic FOR A7
COL editions_enabled FOR A16
COL enabled FOR A7
COL encrypted FOR A9
COL end_date FOR A16
COL enforcement FOR A11
COL entity_name FOR A24
COL entity_type FOR A11
COL error FOR A65 WORD_WRAPPED
COL event_timestamp FOR A32
COL extend_flag FOR A11
COL extended_timestamp FOR A36
COL extent_management FOR A17
COL failure FOR A7
COL fast_refreshable FOR A16
COL first_password_use_occurred FOR A27
COL fk_supp FOR A7
COL flash_cache FOR A11
COL force_logging FOR A13
COL force_nologging FOR A15
COL free FOR A4
COL full_db_caching FOR A15
COL fully_backed_up FOR A15
COL generation_type FOR A15
COL grant_option FOR A12
COL grant_type FOR A10
COL grantable FOR A9
COL granted_role FOR A16
COL grantee FOR A24
COL grantor FOR A24
COL has_default FOR A11
COL has_identity FOR A12
COL hidden_column FOR A13
COL host FOR A20
COL http_enabled FOR A12
COL identity_column FOR A15
COL idx_maintenance_type FOR A20
COL idx_query_stats_enabled FOR A23
COL implicit_destroy FOR A16
COL index_compress_for FOR A18
COL inherited FOR A9
COL initial_group FOR A13
COL inmemory_compression FOR A20
COL inmemory_distribute FOR A19
COL inmemory_duplicate FOR A18
COL inmemory_priority FOR A17
COL instead_of_row FOR A14
COL interval FOR A8
COL invert FOR A6
COL inverted_principal FOR A18
COL is_abstract FOR A11
COL is_admin FOR A8
COL is_application_developer FOR A24
COL is_compiled FOR A11
COL is_debug FOR A8
COL is_default FOR A10
COL is_default_pwd FOR A14
COL is_defaultxts FOR A13
COL is_final FOR A8
COL is_grant FOR A8
COL is_inner FOR A8
COL is_native FOR A9
COL is_nested FOR A9
COL is_proxy_pdb FOR A12
COL is_static FOR A9
COL is_strictfp FOR A11
COL is_synchronized FOR A15
COL is_synthetic FOR A12
COL is_valid FOR A8
COL isadjusted FOR A10
COL isbasic FOR A7
COL isdefault FOR A9
COL isdeprecated FOR A12
COL isinstance_modifiable FOR A21
COL ismodified FOR A10
COL ispdb_modifiable FOR A16
COL isses_modifiable FOR A16
COL issys_modifiable FOR A16
COL job_container FOR A13
COL keep_value FOR A10
COL keystore_mode FOR A13
COL last_analyzed FOR A13
COL last_refresh_type FOR A17
COL limit FOR A32
COL line/col FOR A8
COL locality FOR A8
COL locally_managed FOR A15
COL logon_time FOR A24
COL lost_write_protect FOR A18
COL mandatory_profile_violation FOR A27
COL member FOR A80
COL min_supp FOR A8
COL module FOR A40
COL name FOR A32
COL name_col_plus_show_param FOR A36 HEADING NAME
COL name_col_plus_show_sga FOR A24
COL network_protocol FOR A24
COL no_exp FOR A6
COL no_expdp FOR A8
COL no_stby FOR A7
COL nonschema FOR A9
COL nullable FOR A8
COL obj_name FOR A32
COL object_name FOR A48
COL object_type FOR A11
COL objectname_plus_show_recyc FOR A30 HEADING 'RECYCLEBIN NAME'
COL objtype_plus_show_recyc FOR A12 HEADING 'OBJECT TYPE'
COL open_time FOR A40
COL oracle_maintained FOR A17
COL oracle_supplied FOR A15
COL order_flag FOR A10
COL origname_plus_show_recyc FOR A16 HEADING 'ORIGINAL NAME'
COL owner FOR A24
COL parameter_name FOR A32 WORD_WRAPPED
COL parameter_setting FOR A40
COL parsing_schema FOR A24
COL partitioned FOR A11
COL password FOR A10
COL pattern FOR A24
COL pdb_name FOR A24
COL pk_supp FOR A7
COL pl_supp FOR A7
COL plugged_in FOR A10
COL policy_name FOR A32
COL pool_name FOR A32
COL predicate_evaluation FOR A20
COL principal FOR A20
COL principal_type FOR A14
COL privilege FOR A32
COL process FOR A8
COL profile FOR A32
COL property_name FOR A32
COL property_value FOR A32
COL protected FOR A9
COL proxy FOR A16
COL proxy_only_connect FOR A18
COL proxy_pdb FOR A9
COL push_deferred_rpc FOR A17
COL read_only FOR A9
COL refresh_after_errors FOR A20
COL refresh_method FOR A14
COL refresh_mode FOR A12
COL requires_aco FOR A12
COL restore_only FOR A14
COL restricted FOR A10
COL rewrite_capability FOR A18
COL rewrite_enabled FOR A15
COL rowlabel FOR A15
COL scale_flag FOR A10
COL schedule_type FOR A13
COL schema FOR A30
COL segment_space_management FOR A24
COL segment_subtype FOR A15
COL session_flag FOR A12
COL sharded_flag FOR A12
COL sid FOR 9999999
COL smtp_enabled FOR A12
COL snapshot_mode FOR A13
COL sql_text FOR A60 WORD_WRAPPED
COL start_date FOR A16
COL status FOR A12
COL subpartitioning_type FOR A20
COL success FOR A7
COL sysasm FOR A6
COL sysaux FOR A6
COL sysbackup FOR A9
COL sysdba FOR A6
COL sysoper FOR A7
COL tablespace_name FOR A20
COL template FOR A8
COL temporary FOR A10
COL total_size FOR A12
COL total_size FOR A20
COL uk_supp FOR A7
COL unified_audit_policies FOR A20
COL units_col_plus_show_sga FOR A15
COL updatable FOR A10
COL use_last_archive_timestamp FOR A26
COL user FOR A30
COL user_generated FOR A14
COL user_name FOR A30
COL user_stats FOR A10
COL username FOR A30
COL value FOR A32 WORD_WRAPPED
COL value_col_plus_show_param FOR A30 HEADING VALUE
COL verification_script FOR A20
COL virtual_column FOR A14
COL visibility FOR A10
COL wallet_order FOR A12
COL window_priority FOR A15
COL workspace FOR A24
COL workspace_id FOR 9999999999999999
COL workspace_name FOR A24
COL wrapped FOR A7
