---
- name: Check if utPLSQL is already installed
  shell: |
    set -o pipefail
    source oraenv <<< {{ oracle_sid }} 1>/dev/null
    {{ oracle_home }}/bin/sqlplus -s -L / as sysdba <<-END_HEREDOC
    WHENEVER SQLERROR EXIT SQL.SQLCODE
    SET heading off pages 0
    SELECT REGEXP_SUBSTR(text,'('')(.*)('')',1,1,NULL,2)
      FROM dba_source
     WHERE owner = '{{ schema_name }}' COLLATE binary_ci
       AND name = 'UT_UTILS' COLLATE binary_ci
       AND type = 'PACKAGE'
       AND text LIKE '%gc_version%constant%';
    END_HEREDOC
  environment:
    ORACLE_HOME: "{{ oracle_home }}"
    ORACLE_SID: "{{ oracle_sid }}"
    ORACLE_PDB_SID: "{{ oracle_pdb_name }}"
    PATH: "{{ oracle_home }}/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin"
  changed_when: false
  register: check_utplsql_version

- name: Setup utPLSQL database schema
  include_role:
    name: oracle_app_schema
  when: check_utplsql_version.stdout != software_version
