---
- name: Manage directory on disk
  file:
    path: "{{ item.directory_path }}"
    state: "{{ item.state }}"
    owner: "{{ oracle_user }}"
    group: "{{ oracle_install_group }}"
    mode: "u=rwx,go="
  loop: "{{ passed_list }}"

- name: Check Oracle Database directory object existence
  shell: |
    set -o pipefail
    source oraenv <<< {{ oracle_sid }} 1>/dev/null
    {{ oracle_home }}/bin/sqlplus -s -L / as sysdba <<-'END_HEREDOC'
    WHENEVER SQLERROR EXIT SQL.SQLCODE
    SET heading off pages 0
    SELECT NVL(MAX(true),false)
      FROM dba_directories
     WHERE directory_name = '{{ item.directory_name }}' COLLATE binary_ci
       AND directory_path = '{{ item.directory_path }}' COLLATE binary_ci;
    END_HEREDOC
  environment:
    ORACLE_HOME: "{{ oracle_home }}"
    ORACLE_SID: "{{ oracle_sid }}"
    ORACLE_PDB_SID: "{{ oracle_pdb_name }}"
    PATH: "{{ oracle_home }}/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin"
  become: true
  become_user: "{{ oracle_user }}"
  changed_when: false
  register: check_oracle_directory_objects
  loop: "{{ passed_list }}"

- name: Add Oracle Database directory object
  shell: |
    set -o pipefail
    source oraenv <<< {{ oracle_sid }} 1>/dev/null
    {{ oracle_home }}/bin/sqlplus -s -L / as sysdba <<-'END_HEREDOC'
    WHENEVER SQLERROR EXIT SQL.SQLCODE
    CREATE OR REPLACE DIRECTORY {{ item.directory.directory_name }} AS '{{ item.directory.directory_path }}';
    END_HEREDOC
  environment:
    ORACLE_HOME: "{{ oracle_home }}"
    ORACLE_SID: "{{ oracle_sid }}"
    ORACLE_PDB_SID: "{{ oracle_pdb_name }}"
    PATH: "{{ oracle_home }}/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin"
  become: true
  become_user: "{{ oracle_user }}"
  when:
    - item.directory.state | lower == "directory"
    - not item.dir_found | bool
  loop: "{{ check_oracle_directory_objects | json_query('results[*].{directory:item,dir_found:stdout}') }}"

- name: Remove Oracle Database directory object
  shell: |
    set -o pipefail
    source oraenv <<< {{ oracle_sid }} 1>/dev/null
    {{ oracle_home }}/bin/sqlplus -s -L / as sysdba <<-'END_HEREDOC'
    WHENEVER SQLERROR EXIT SQL.SQLCODE
    DROP DIRECTORY {{ item.directory.directory_name }};
    END_HEREDOC
  environment:
    ORACLE_HOME: "{{ oracle_home }}"
    ORACLE_SID: "{{ oracle_sid }}"
    ORACLE_PDB_SID: "{{ oracle_pdb_name }}"
    PATH: "{{ oracle_home }}/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin"
  become: true
  become_user: "{{ oracle_user }}"
  when:
    - item.directory.state | lower == "absent"
    - item.dir_found | bool
  loop: "{{ check_oracle_directory_objects | json_query('results[*].{directory:item,dir_found:stdout}') }}"
