---
- name: Check Oracle Database profile existence
  shell: |
    set -o pipefail
    source oraenv <<< {{ oracle_sid }} 1>/dev/null
    {{ oracle_home }}/bin/sqlplus -s -L / as sysdba <<-'END_HEREDOC'
    WHENEVER SQLERROR EXIT SQL.SQLCODE
    SET heading off pages 0
    SELECT NVL(MAX(true),false)
      FROM dba_profiles
     WHERE profile = '{{ item.profile_name }}' COLLATE binary_ci;
    END_HEREDOC
  environment:
    ORACLE_HOME: "{{ oracle_home }}"
    ORACLE_SID: "{{ oracle_sid }}"
    ORACLE_PDB_SID: "{{ oracle_pdb_name }}"
    PATH: "{{ oracle_home }}/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin"
  become: true
  become_user: "{{ oracle_user }}"
  changed_when: false
  register: check_oracle_profile
  loop: "{{ passed_list }}"

- name: Add Oracle Database profile
  shell: |
    set -o pipefail
    source oraenv <<< {{ oracle_sid }} 1>/dev/null
    {{ oracle_home }}/bin/sqlplus -s -L / as sysdba <<-'END_HEREDOC'
    WHENEVER SQLERROR EXIT SQL.SQLCODE
    -- Use an arbitrary initial limit to make the DDL syntactically correct
    CREATE PROFILE {{ item.profile.profile_name }} LIMIT sessions_per_user default;
    END_HEREDOC
  environment:
    ORACLE_HOME: "{{ oracle_home }}"
    ORACLE_SID: "{{ oracle_sid }}"
    ORACLE_PDB_SID: "{{ oracle_pdb_name }}"
    PATH: "{{ oracle_home }}/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin"
  become: true
  become_user: "{{ oracle_user }}"
  when:
    - item.profile.state | lower == "present"
    - not item.profile_found | bool
  loop: "{{ check_oracle_profile | json_query('results[*].{profile:item,profile_found:stdout}') }}"

- name: Remove Oracle Database profile
  shell: |
    set -o pipefail
    source oraenv <<< {{ oracle_sid }} 1>/dev/null
    {{ oracle_home }}/bin/sqlplus -s -L / as sysdba <<-'END_HEREDOC'
    WHENEVER SQLERROR EXIT SQL.SQLCODE
    DROP PROFILE {{ item.profile.profile_name }} CASCADE;
    END_HEREDOC
  environment:
    ORACLE_HOME: "{{ oracle_home }}"
    ORACLE_SID: "{{ oracle_sid }}"
    ORACLE_PDB_SID: "{{ oracle_pdb_name }}"
    PATH: "{{ oracle_home }}/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin"
  become: true
  become_user: "{{ oracle_user }}"
  when:
    - item.profile.state | lower == "absent"
    - item.profile_found | bool
  loop: "{{ check_oracle_profile | json_query('results[*].{profile:item,profile_found:stdout}') }}"
