---
- name: Check Oracle Database proxy privilege existence
  shell: |
    set -o pipefail
    source oraenv <<< {{ oracle_sid }} 1>/dev/null
    {{ oracle_home }}/bin/sqlplus -s -L / as sysdba <<-'END_HEREDOC'
    WHENEVER SQLERROR EXIT SQL.SQLCODE
    SET heading off pages 0
    SELECT NVL(MAX(true),false)
      FROM proxy_users
     WHERE proxy = '{{ item.proxy_name }}' COLLATE binary_ci
       AND client = '{{ item.proxy_client }}' COLLATE binary_ci;
    END_HEREDOC
  environment:
    ORACLE_HOME: "{{ oracle_home }}"
    ORACLE_SID: "{{ oracle_sid }}"
    ORACLE_PDB_SID: "{{ oracle_pdb_name }}"
    PATH: "{{ oracle_home }}/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin"
  become: true
  become_user: "{{ oracle_user }}"
  changed_when: false
  register: check_oracle_proxy_privs
  loop: "{{ passed_list }}"

- name: Add Oracle Database proxy privilege
  shell: |
    set -o pipefail
    source oraenv <<< {{ oracle_sid }} 1>/dev/null
    {{ oracle_home }}/bin/sqlplus -s -L / as sysdba <<-'END_HEREDOC'
    WHENEVER SQLERROR EXIT SQL.SQLCODE
    ALTER USER {{ item.proxy.proxy_client }} GRANT CONNECT THROUGH {{ item.proxy.proxy_name }} {{ item.proxy.proxy_options }};
    END_HEREDOC
  environment:
    ORACLE_HOME: "{{ oracle_home }}"
    ORACLE_SID: "{{ oracle_sid }}"
    ORACLE_PDB_SID: "{{ oracle_pdb_name }}"
    PATH: "{{ oracle_home }}/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin"
  become: true
  become_user: "{{ oracle_user }}"
  when:
    - item.proxy.state | lower == "present"
    - not item.grant_found | bool
  loop: "{{ check_oracle_proxy_privs | json_query('results[*].{proxy:item,grant_found:stdout}') }}"

- name: Remove Oracle Database proxy privilege
  shell: |
    set -o pipefail
    source oraenv <<< {{ oracle_sid }} 1>/dev/null
    {{ oracle_home }}/bin/sqlplus -s -L / as sysdba <<-'END_HEREDOC'
    WHENEVER SQLERROR EXIT SQL.SQLCODE
    ALTER USER {{ item.proxy.proxy_client }} REVOKE CONNECT THROUGH {{ item.proxy.proxy_name }};
    END_HEREDOC
  environment:
    ORACLE_HOME: "{{ oracle_home }}"
    ORACLE_SID: "{{ oracle_sid }}"
    ORACLE_PDB_SID: "{{ oracle_pdb_name }}"
    PATH: "{{ oracle_home }}/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin"
  become: true
  become_user: "{{ oracle_user }}"
  when:
    - item.proxy.state | lower == "absent"
    - item.grant_found | bool
  loop: "{{ check_oracle_proxy_privs | json_query('results[*].{proxy:item,grant_found:stdout}') }}"
