---
- name: Install required and recommended packages
  dnf:
    name: "{{ base_packages }}"
    state: present
    lock_timeout: "{{ dnf_lock_timeout }}"

- name: Set timezone
  command: timedatectl set-timezone {{ server_timezone }}
