---
smtp_server: mail.shaw.ca
smtp_sender_domain: shaw.ca
smtp_recipient_domain: pythian.com
smtp_sender_db: "simon.pane.2"
smtp_sender_apex: "simon.pane.2"

main_user_email: pane@pythian.com
notification_user_email: pane@pythian.com
send_notification_email: false

server_timezone: America/Edmonton
